<?php

/**
 * @file
 * Syncs the access list with Active Directory group(s).
 */


/**
 * Implements hook_cron().
 */
function isushibsiteaccesssync_cron() {
  $ad_username = variable_get('isushibsiteaccesssync_ad_username', '');
  $ad_password = variable_get('isushibsiteaccesssync_ad_password', '');
  $ad_group_names = explode(',', variable_get('isushibsiteaccesssync_ad_group_names', ''));
  $ad_ldap_server = variable_get('isushibsiteaccesssync_ad_ldap_server', 'windc.iastate.edu');
  $ad_ldap_dn = variable_get('isushibsiteaccesssync_ad_ldap_dn', 'dc=iastate,dc=edu');

  // Exit if we don't have the variables that we need.
  $ad_group_names = array_filter($ad_group_names);
  if ($ad_username == '' || $ad_password == '' || empty($ad_group_names)) {
    return;
  }

  // Make sure we have LDAP extensions installed
  if (!function_exists('ldap_connect')) {
    watchdog('isushibsiteaccesssync', 'PHP LDAP extensions not installed, exiting.');
    return;
  }

  $ad_group_names = array_map('trim', $ad_group_names);
  foreach ($ad_group_names as $ad_group_name) {
    watchdog('isushibsiteaccesssync', t('*%name*', array('%name' => $ad_group_name)));
  }
}